# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: WebApp-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
          # super_secret: ${{ secrets.REACT_APP_OPENWEATHER_APIKEY }}
        env:
          REACT_APP_WEATHER_API_KEY: ${{ secrets.REACT_APP_WEATHER_API_KEY }}
          REACT_APP_MOVIE_API_KEY_v3: ${{ secrets.REACT_APP_MOVIE_API_KEY_v3 }}
      - name: npm install, build and test
        run: |
          npm install --legacy-peer-deps
      #    npm run build --if-present
      #    npm test
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test
